spring:
  redis:
    database: 0
# 单机版配置
#    host: 127.0.0.1
#    用于Docker部署, 采用别名，不用具体IP
    host: redis-server
    port: 6379
# 集群配置
#    cluster:
#      max-redirects: 1
#      nodes:
#        - 127.0.0.1:7010
#        - 127.0.0.1:7011
#        - 127.0.0.1:7012
#    password:
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    timeout: 1000

  ## 为了测试方便，这里数据库持久层采用 h2 数据库
  datasource:
    data: classpath:db/data.sql
    schema: classpath:db/schema.sql
    url: jdbc:h2:mem:dbtest
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2
    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


### 开启自动类型转换，多个以逗号分隔
#fastjson:
#  parser:
#    autoTypeSupport: true
#    autoTypeAccept: com.liuyanzhao.entity.
